### ISSUE TITLE
Requirements for glom install in conda are incorrectly overly-restrictive for `attrs` package (conflicting with pytest)

### ISSUE THREAD

**Issue by sjdemartini** [conda-forge/glom-feedstock#11]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The requirements specified here in glom-feedstock for the conda-install of glom are overly-restrictive, specifying that the `attrs` package must be `<=19.1.0`:

https://github.com/conda-forge/glom-feedstock/blob/0efc8c424a2ce6e47e959564bac125942a33507f/recipe/meta.yaml#L24

While the standard `setup.py` for the pip-install of glom does *not* specify a version requirement for the `attrs` package:

https://github.com/mahmoud/glom/blob/e677614386116ceb5f018d47be9e3d2d907dbbce/setup.py#L33

Perhaps this was intended to be `>=19.1.0` instead of `<=`? The 19.1.0 version of `attrs` was released in [March 2019](https://www.attrs.org/en/stable/changelog.html#id30) so is quite outdated. Packages such as pytest require `attrs` to be `>= 19.2.0` (where that requirement has been in place [since Dec 2020](https://docs.pytest.org/en/7.1.x/changelog.html#id145)), so `glom` and `pytest` cannot both reasonably be installed in a conda environment right now, for instance.

### Installed packages

```shell
pytest >= 6.2 
```

### Environment info

```shell
n/a
```

**Comment by sjdemartini** [comment]
@thewchan pinging you since you added the `attrs` restriction in https://github.com/conda-forge/glom-feedstock/pull/8 in September 2022 and might have more context here and be able to resolve. Thank you!

**Comment by thewchan** [comment]
Let's see if this https://github.com/conda-forge/glom-feedstock/pull/12 can fix it

**Comment by sjdemartini** [comment]
That did seem to do the trick for me, thanks so much for the super quick turnaround!
